route:
  receiver: 'slack-notifications'
  group_by: ['alertname', 'job']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h

receivers:
  - name: 'slack-notifications'
    slack_configs:
      - channel: '#alerts'
        send_resolved: true


# group_by	Groups alerts with same alertname and job into one message
# group_wait	Waits 30s before sending first alert (to collect more for grouping)
# group_interval	Waits 5 min between alert messages for same group
# repeat_interval	Resends grouped alerts every 1 hour if they persist