# helm upgrade --install alloy grafana/alloy -n alloy --create-namespace -f alloy-values.yaml

controller:
  type: deployment
  replicas: 1

rbac:
  create: true

# extraRBAC:
#   create: true
#   rules:
#     - apiGroups: [""]
#       resources: ["pods", "pods/log", "namespaces"]
#       verbs: ["get", "list", "watch"]

service:
  enabled: true
  ports:
    - name: otlp-grpc
      port: 4317
      targetPort: 4317
    - name: otlp-http
      port: 4318
      targetPort: 4318

alloy:
  mounts:
    varlog: false
    dockercontainers: false

  configMap:
    create: true
    content: |
      // Discover Kubernetes pods
      discovery.kubernetes "pods" {
        role = "pod"
      }

      // Relabel to add metadata
      discovery.relabel "pod_logs" {
        targets = discovery.kubernetes.pods.targets
        rule {
          source_labels = ["__meta_kubernetes_namespace"]
          target_label = "namespace"
        }
        rule {
          source_labels = ["__meta_kubernetes_pod_name"]
          target_label = "pod"
        }
        rule {
          source_labels = ["__meta_kubernetes_pod_container_name"]
          target_label = "container"
        }
        rule {
          source_labels = ["__meta_kubernetes_pod_label_app"]
          target_label = "app"
        }
        rule {
          action = "replace"
          source_labels = [""]
          target_label = "job"
          replacement = "kubernetes-pods"
        }
      }

      // Tail logs via Kubernetes API
      loki.source.kubernetes "k8s_logs" {
        targets    = discovery.relabel.pod_logs.output
        forward_to = [loki.write.default.receiver]
      }

      loki.write "default" {
        endpoint {
          url = "http://loki-gateway.loki.svc.cluster.local/loki/api/v1/push"
        }
      }
