---
# Namespace
apiVersion: v1
kind: Namespace
metadata:
  name: tracing
---
# 1) EBS-backed PVC for Tempo data (gp3)
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tempo-data
  namespace: tracing
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: gp3
