---
# Namespace
apiVersion: v1
kind: Namespace
metadata:
  name: tracing
---
# 1) EBS-backed PVC for Tempo data (gp3)
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tempo-data
  namespace: tracing
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: gp3
---
global:
  storage:
    trace:
      backend: local  # Use local PVCs instead of S3
      local:
        path: /var/tempo  # Storage path in container

serviceAccount:
  create: true
  annotations: {}  # No IRSA needed for local storage

distributor:
  enabled: true
  replicas: 1

ingester:
  enabled: true
  replicas: 1
  persistence:
    enabled: true
    storageClass: gp3  # Use gp3 StorageClass
    size: 10Gi  # Adjust as needed

querier:
  enabled: true
  replicas: 1

compactor:
  enabled: true
  replicas: 1
  persistence:
    enabled: true
    storageClass: gp3
    size: 10Gi

gateway:
  enabled: true  # For HTTP access, similar to Loki setup

traces:
  otlp:
    grpc: true  # HotROD uses OTLP/gRPC
    http: true  # Optional for flexibility
---
# 5) HotROD demo app (send traces to Tempo over Jaeger HTTP)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotrod
  namespace: tracing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hotrod
  template:
    metadata:
      labels:
        app: hotrod
    spec:
      containers:
        - name: hotrod
          image: jaegertracing/example-hotrod:latest
          env:
            # Use HTTP ingestion (more reliable than UDP for labs)
            - name: JAEGER_ENDPOINT
              value: "http://tempo.tracing.svc.cluster.local:14268/api/traces"
            # Ensure agent mode is not used
            - name: JAEGER_AGENT_HOST
              value: ""
          ports:
            - containerPort: 8080
---
# 6) HotROD Service (ClusterIP; port-forward to access)
apiVersion: v1
kind: Service
metadata:
  name: hotrod
  namespace: tracing
spec:
  selector:
    app: hotrod
  ports:
    - port: 8080
      targetPort: 8080
      name: http
