apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: aws-secret-store
spec:
  provider:
    aws:
      service: SecretsManager
      region: eu-central-1
      auth:
        secretRef:
          accessKeyID:
            name: aws-creds
            key: access-key
          secretAccessKey:
            name: aws-creds
            key: secret-key
